// <auto-generated />
namespace BlueEconomics.Platform.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddForeignKeyIndustryInOccupationTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddForeignKeyIndustryInOccupationTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201306240237278_AddForeignKeyIndustryInOccupationTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
